"use client";

import { ShieldCheck } from "lucide-react";

import type { MfaPreparation } from "@/lib/auth/mfa";

type Props = {
  preparation: MfaPreparation;
  code: string;
  verifying: boolean;
  onCodeChange: (value: string) => void;
  onVerify: () => Promise<void>;
  onCancel: () => Promise<void>;
};

export function MfaChallengePage({
  preparation,
  code,
  verifying,
  onCodeChange,
  onVerify,
  onCancel,
}: Props) {
  const enrolling = preparation.mode === "enroll";

  return (
    <main className="flex min-h-dvh items-center justify-center bg-[#f7f9fb] px-5 py-10">
      <section className="w-full max-w-lg rounded-[30px] border border-slate-200 bg-white px-6 py-8 shadow-[0_22px_55px_rgba(15,23,42,0.10)] sm:px-10 sm:py-10">
        <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-50 text-teal-700">
          <ShieldCheck className="h-6 w-6" aria-hidden="true" />
        </div>

        <h1 className="mt-6 text-3xl font-bold tracking-tight text-slate-950">
          {enrolling
            ? "Set up multi-factor authentication"
            : "Verify your identity"}
        </h1>

        <p className="mt-3 text-base leading-7 text-slate-600">
          {enrolling
            ? "Your Castodia role requires an authenticator app. Scan the QR code, then enter the 6-digit code generated by the app."
            : "Enter the 6-digit code from your authenticator app to continue."}
        </p>

        {preparation.mode === "enroll" ? (
          <div className="mt-7 rounded-2xl border border-slate-200 bg-slate-50 p-5">
            <img
              src={preparation.qrCode}
              alt="QR code for adding Castodia to your authenticator app"
              className="mx-auto h-52 w-52 rounded-xl bg-white p-2"
            />

            <p className="mt-5 text-center text-sm text-slate-500">
              If you cannot scan the QR code, enter this setup key manually:
            </p>

            <p className="mt-2 break-all rounded-xl bg-white px-3 py-2 text-center font-mono text-sm font-semibold text-slate-800">
              {preparation.secret}
            </p>
          </div>
        ) : null}

        <form
          className="mt-7 space-y-5"
          onSubmit={(event) => {
            event.preventDefault();
            void onVerify();
          }}
        >
          <div>
            <label
              htmlFor="mfa-code"
              className="mb-2 block text-sm font-semibold text-slate-800"
            >
              Authentication code
            </label>

            <input
              id="mfa-code"
              name="mfa-code"
              type="text"
              inputMode="numeric"
              autoComplete="one-time-code"
              pattern="[0-9]{6}"
              maxLength={6}
              required
              autoFocus
              value={code}
              onChange={(event) =>
                onCodeChange(event.target.value.replace(/\D/g, "").slice(0, 6))
              }
              disabled={verifying}
              className="h-14 w-full rounded-2xl border border-slate-300 bg-slate-50 px-4 text-center font-mono text-xl tracking-[0.35em] text-slate-950 outline-none transition focus:border-teal-500 focus:bg-white focus:ring-4 focus:ring-teal-100 disabled:cursor-not-allowed disabled:opacity-60"
              placeholder="000000"
            />
          </div>

          <button
            type="submit"
            disabled={verifying || code.length !== 6}
            className="flex h-14 w-full items-center justify-center rounded-2xl bg-gradient-to-r from-[#079c9c] to-[#65d0c7] px-5 text-base font-bold text-white shadow-[0_12px_28px_rgba(13,148,136,0.24)] transition hover:brightness-105 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-teal-200 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {verifying ? "Verifying..." : enrolling ? "Complete setup" : "Verify and continue"}
          </button>

          <button
            type="button"
            onClick={() => void onCancel()}
            disabled={verifying}
            className="w-full text-center text-sm font-semibold text-slate-600 transition hover:text-slate-900 hover:underline disabled:cursor-not-allowed disabled:opacity-60"
          >
            Cancel and sign out
          </button>
        </form>
      </section>
    </main>
  );
}
