// lib/training/suggestedCourses.ts

export const suggestedTrainingCourses = [
  "Safeguarding Adults",
  "Safeguarding Children",
  "Medication Administration",
  "Infection Prevention and Control",
  "Fire Safety",
  "Health and Safety",
  "Moving and Handling",
  "Food Safety",
  "Emergency First Aid at Work",
  "Basic Life Support",
  "Mental Capacity Act",
  "DoLS and Liberty Protection Safeguards",
  "Equality, Diversity and Inclusion",
  "GDPR and Data Protection",
  "Duty of Candour",
  "Lone Working",
  "Positive Behaviour Support",
  "Autism Awareness",
  "Learning Disability Awareness",
  "Dementia Awareness",
  "Epilepsy Awareness",
  "COSHH",
  "Risk Assessment",
  "Professional Boundaries",
  "Record Keeping",
] as const;